use_frameworks!

target 'PodWithOtherDependecy_Example' do
  pod 'M13Checkbox'
  pod 'SkyFloatingLabelTextField', '~> 3.0'
  pod 'TagListView', '~> 1.0'
  pod 'PodWithOtherDependecy', :path => '../'

  target 'PodWithOtherDependecy_Tests' do
    inherit! :search_paths

    
  end
end
